sendgrid_api_key: ''
ip: '172.16.57.50:5000'
num_threads: 2
mapper_threads: 2
mongo_url: 'mongodb://localhost:27017/'
email_address: 'RnaSeqAnalysisSuite@rutgers.edu'
library-type:
  - fr-unstranded
  - fr-firststrand
  - fr-secondstrand
genome_files:
  - name: 'mouse (mm10)'
    gtf: '/home/nk371/Mouse_data/Mus_musculus/UCSC/mm10/Annotation/genes.gtf'
    genome: '/home/nk371/Mouse_data/Mus_musculus/UCSC/mm10/Sequence/Bowtie2Index/genome'
  - name: 'mouse (mm9)'
    gtf: '/home/nk371/Mus_musculus/UCSC/mm9/Annotation/Genes/genes.gtf'
    genome: '/home/nk371/Mus_musculus/UCSC/mm9/Sequence/Bowtie2Index/genome'