library('cummeRbund')
#library('ggplot2')
args <- commandArgs(trailingOnly=TRUE)
error_file <- file(args[1], open="wt")
sink(error_file, type="message")
cuff <- readCufflinks()
#dend<-csDendro(genes(cuff))
#print(dend)
#ggsave(args[2], width = 10, height = 10,dpi=600)
png(args[2],width = 10, height = 10, units= 'in',res=600)
csDendro(genes(cuff))
dev.off()
#print(args[2])