library(cummeRbund)
args <- commandArgs(trailingOnly=TRUE)
error_file <- file(args[1], open="wt")
sink(error_file, type="message")
cuff <- readCufflinks()
mySigGeneIds<-getSig(cuff,x=args[2],y=args[3],alpha=as.double(args[4]),level='genes')
genes_length <- length(mySigGeneIds)
write(genes_length,file="number_of_sig_genes.Rout")
mySigGenes<-getGenes(cuff,mySigGeneIds)
saveRDS(mySigGenes,'significant_genes.rds')
