library(cummeRbund)
args <- commandArgs(trailingOnly=TRUE)
error_file <- file(args[1], open="wt")
sink(error_file, type="message")
cuff <- readCufflinks()
similar_genes<-findSimilar(cuff,args[3],n=args[4])
similar_expression<-expressionPlot(similar_genes,logMode=T,showErrorbars=F)
png(args[2],width = 10, height = 10, units= 'in',res=600)
print(similar_expression)
dev.off()