library(cummeRbund)
args <- commandArgs(trailingOnly=TRUE)
error_file <- file(args[1], open="wt")
sink(error_file, type="message")
cuff <- readCufflinks()
sig_genes <- readRDS('significant_genes.rds')
heatmap<-csHeatmap(sig_genes,cluster='both')
png(args[2],width = 10, height = 20, units= 'in',res=600)
print(heatmap)
dev.off()