library(cummeRbund)
args <- commandArgs(trailingOnly=TRUE)
error_file <- file(args[1], open="wt")
sink(error_file, type="message")
cuff <- readCufflinks()
mySigGeneIds<-getSig(cuff,alpha=as.double(args[2]),level='genes')
genes_length <- length(mySigGeneIds)
write(genes_length,file="number_of_sig_genes.Rout")
mySigGenes<-getGenes(cuff,mySigGeneIds)
saveRDS(mySigGenes,'significant_genes.rds')
